home:
    path: /
    defaults: { _controller: App\Controller\HomeController:homeAction }

listPosts_paginated:
    path: /listPosts/{page}
    defaults: { _controller: App\Controller\PostController:listPostsAction, page: 1 }
    requirements:
        page: '\d+'

post:
    path: post/{id}
    defaults: { _controller: App\Controller\PostController:singlePost }
    requirements:
        id: '\d+'

contact:
    path: /contact
    defaults: { _controller: App\Controller\ContactController:contactAction }

register_user:
    path: /register
    defaults: { _controller: App\Controller\UserController:registerUserAction }

recovery_username_user:
    path: /recoveryusername
    defaults: { _controller: App\Controller\UserController:recoveryUsernameUserAction }

reset_password_user:
    path: /resetpassword
    defaults: { _controller: App\Controller\UserController:resetPasswordUserAction }

new_password_user:
    path: /newpassword/{token}
    defaults: { _controller: App\Controller\UserController:newPasswordUserAction }

newPost:
    path: admin/newPost
    defaults: { _controller: App\Controller\Admin\PostController:newPostAction }

managePosts:
    path: admin/managePosts/{page}
    defaults: { _controller: App\Controller\Admin\PostController:managePostsAction, page: 1 }
    requirements:
        page: '\d+'

deletePost:
    path: admin/deletePost/{id}
    defaults: { _controller: App\Controller\Admin\PostController:deletePostAction }
    requirements:
        page: '\d+'

updatePost:
    path: admin/post/update/{id}
    defaults: { _controller: App\Controller\Admin\PostController:updatePostAction }
    requirements:
        id: '\d+'

manageComments:
    path: admin/manageComments/{page}
    defaults: { _controller: App\Controller\Admin\CommentController:manageCommentsAction, page: 1 }
    requirements:
        page: '\d+'

deleteComment:
    path: admin/deleteComment/{id}
    defaults: { _controller: App\Controller\Admin\CommentController:deleteCommentAction }
    requirements:
        id: '\d+'

validationComment:
    path: admin/validationComment/{id}
    defaults: { _controller: App\Controller\Admin\CommentController:validationCommentAction }
    requirements:
        id: '\d+'

login:
     path: /login
     defaults: { _controller: App\Controller\SecurityController:loginAction }

login_check:
    path: /login/check
    defaults: { _controller: App\Controller\SecurityController:loginCheckAction }

logout:
    path: /logout
    defaults: { _controller: App\Controller\SecurityController:logoutAction }

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
